### ISSUE TITLE
[BUG] Plugin replaces not only publicPath ('/' in my case) variable but also randomly some '/' across the application.

### ISSUE THREAD

**Issue by Oleksandr-Korniienko-IS** [zahorovskyi/webpack-dynamic-public-path#8]
![image](https://user-images.githubusercontent.com/55439839/110007665-9a3dc980-7d23-11eb-9fd6-4efcced9d18c.png)
![image](https://user-images.githubusercontent.com/55439839/110007681-9e69e700-7d23-11eb-950d-19fb1e20affe.png)
![image](https://user-images.githubusercontent.com/55439839/110007692-a1fd6e00-7d23-11eb-9c3f-a77db04ec56b.png)
![image](https://user-images.githubusercontent.com/55439839/110007803-bccfe280-7d23-11eb-8a92-d6f31959d81d.png)

**Comment by Oleksandr-Korniienko-IS** [comment]
the Webpack has similar behavior with __webpack_public_path__ https://webpack.js.org/guides/public-path/#on-the-fly

**Comment by zahorovskyi** [comment]
Hi @Oleksandr-Korniienko-IS,
First of all, thanks for your participation! :smile:

Yes, it makes direct string replacement, and this is expected behavior. That's why `publicPath` should be a unique string, for example, `publicPathPlaceholder`, or whoever you want, but not just a slash.
About `webpack_public_path` - actually, this feature works similarly because `DefinePlugin`(it required there) makes direct string replacement too.
From `DefinePlugin` documentation(https://webpack.js.org/plugins/define-plugin/#usage):
```
Note that because the plugin does a direct text replacement, the value given to it must include actual quotes inside the string itself. Typically, this is done either with alternate quotes, such as '"production"', or by using JSON.stringify('production').
```
That's why guys from `webpack` team ask you to use a unique string, like `process.env.ASSET_PATH`, so I believe that you will have the same issue with a slash.
If `webpack` fits your needs, you can use it, but I'd suggest to use another string template anyway.
